include: package:flutter_lints/flutter.yaml

# Additional lint rules and customizations
linter:
  rules:
    # Allow print statements in development (disable for production)
    avoid_print: false
    # Allow BuildContext across async gaps with proper checks
    use_build_context_synchronously: false
    # Allow dangling library doc comments
    dangling_library_doc_comments: false

# Analyzer settings
analyzer:
  exclude:
    # Exclude generated files
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    # Exclude build directory
    - "build/**"
    # Exclude test files from some rules
    - "test/**"
  
  # Ignore missing dependencies that are intentionally not included
  errors:
    # Treat these as warnings instead of errors for CI
    uri_does_not_exist: warning
    undefined_class: warning
    undefined_identifier: warning
    non_type_as_type_argument: warning
    undefined_method: warning
    non_type_in_catch_clause: warning
    depend_on_referenced_packages: ignore
    
  # Strong mode settings
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false